geerlingguy/ansible-role-homebrew

- tasks/main.yml
Before this commit, any formulas in the homebrew_installed_packages list that were from taps would fail to install on a fresh system (or where the taps have yet to be tapped).  For example, using the playbook from https://github.com/geerlingguy/mac-dev-playbook would result in an error as the formula 'brew-cask' cannot be found.
> Ensure configured taps are tapped before packages are installed.

- tasks/main.yml
Fixes #11 by using a login shell.
> Fix for brew cask not found on remote machines

- tasks/main.yml
```
TASK: [geerlingguy.homebrew | Ensure homebrew is installed.] ****************** 
failed: [vm] => {"cmd": "/usr/bin/git clone --origin origin --branch master git://github.com/Homebrew/homebrew.git /usr/local", "failed": true, "rc": 128}
stderr: fatal: destination path '/usr/local' already exists and is not an empty directory.
msg: fatal: destination path '/usr/local' already exists and is not an empty directory.
FATAL: all hosts have already failed -- abortin
```
> update bin perms after homebrew is installed else fail like this

- tasks/main.yml
Newer versions of Ansible use `become`, and offer a deprecation warning if using the sudo parameter.
> switch sudo to become

- tasks/main.yml
Fix provided as a result of the discussion here https://github.com/geerlingguy/mac-dev-playbook/issues/27 
I found that the ansible task would execute fine but silently it would not complete the required linking between /usr/local/bin and packages in /usr/local/Cellar. This would result in no packages being available on the path
The breaking change with Sierra macOS is pretty much summed up here http://apple.stackexchange.com/questions/261695/new-mbp-with-sierra-usr-local-bin-no-longer-accessible-unless-root
> Fix Sierra macOS issue with dir ownership which was preventing linking brew packages

- .travis.yml
- README.md
- meta/main.yml
- requirements.yml
- tasks/main.yml
Summary of Changes
==================
Since the OS X Command Line Tools are a hard dependency for Homebrew, this
role will now make sure that they are installed. If they are already
installed, those steps will be skipped. This makes using this role easier
to use when provisioning MacOS, especially when the destination host is not
the same as the control node.
Other related changes:
* `meta/main.yml`: specifies platform `MacOSX` instead of `GenericUNIX`
* `.travis.yml`: Fix homebrew uninstall process-- the old way hangs.
* `tasks/main.yml`: Ensure `root` is the owner of `homebrew_prefix` (`/usr/local`)
> Install OSX command line tools

- tasks/main.yml
The `setup` task module gathers facts and populates the
`ansible_user_id` variable. This seems to be a simpler way of
determining the user responsible for managing the homebrew installation.
See `ansible-doc setup` for more information about the `setup` module.
> Replace homebrew_whoami with ansible_user_id

- tasks/main.yml
Since CLI options are supported (e.g. appdir), this is now usable.
This change removes an extraneous command-module task and switches
to using the homebrew_cask module for installing Homebrew casks.
> Use the homebrew_cask module

- meta/main.yml
Fixes this deprecation warning received upon install:
```
[DEPRECATION WARNING]: The comma separated role spec format, use the yaml/explicit format instead..
This feature will be removed in a future release.                                                                                                            
Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.   
```
https://github.com/debops/ansible-sshd/issues/35#issuecomment-223684840
> Resolve deprecation warning

- tasks/main.yml
Specify packages that should _not_ be installed via `{{ homebrew_uninstalled_packages }}`.
> Add ability to uninstall packages

- tasks/main.yml
Installed 10.13 (High Sierra) and found this to be needed.
The home-brew /usr/local dir does not need to be owned by admin (or have a 775 mode).
> Relax /usr/local directory owner and permissions check.

- tasks/main.yml
If High Sierra, use different permissions for '/usr/local' that when older version of Mac OS X.
This should fix #76 . Not sure if what I did is the best way to test for a Mac OS X version, but I reckon it's probably good enough.
> Added check for Mac OS X version.

- tasks/main.yml
For Java devs this is a fundamental set up. Maven is a core Java build tool, and would be standard in most set ups. Java is provided as a cask and needs to be installed prior to brew install on any packages which run on Java. 
Those who do not use Maven would likely use Gradle
This also affects installs such as [elastic search](http://www.inanzzz.com/index.php/post/wv82/solution-for-elasticsearch-java-is-required-to-install-this-formula-in-mac-os)
> Put install tasks for cask before brew to fix dependencies on Java

- .travis.yml
To facilitate maintenance, this change adds some missing  MacOS X
versions to the Travis CI test matrix, including Sierra (10.12) and
High Sierra (10.13) BETA. Subsequent bugfixes and enhancements
should demonstrably pass and do what they claim on more up-to-date
systems. I've added Yosemite (10.10) as an item to the test matrix
as well, but more priority should be given to the latest OS.
> Additional OS versions in Travis CI test

- README.md
- meta/main.yml
- requirements.yml
- tests/test.yml
This reverts commit e1efb76a448de96f73cc06c8711d473313ed9cda.
Related to ansible/galaxy#775
> Revert "Use underscores instead of dashes for dependencies"

- tasks/main.yml
This change fixes a potential security vulnerability that arises
when cloning the Homebrew repository over SSH. The default case
uses anonymous HTTPS from GitHub, so most users probably won't be
impacted.
If a potential user is impacted by this change, the host key can
be cached for the "first time" by combining the `ssh-keyscan`
command with the `known_hosts` Ansible module. These steps could be
taken during a playbook's `pre_tasks`.
Fixes #102
> Don't accept SSH host key by default

- meta/main.yml
- tasks/main.yml
I checked to see if there was any better way to check the OS version but couldn't really see a good one since the major version is always 10. Let me know if there's a better way to do this check.
> Support 10.14 when checking directory permissions

- README.md
- defaults/main.yml
- handlers/main.yml
- tasks/main.yml
- tests/test.yml
Summary of Changes
==================
This change provides the option to clear the Homebrew cache after any software
installation. The handler will only run if the related role variable is set.
Why?
----
The benefit is that this saves disk space and can avoid installation/execution
of potentially corrupt software, but the cost is the time saved by avoiding
re-downloading what were otherwise cached files (fixes #40).
> Enhancement - Clear Caches

- defaults/main.yml
- tasks/main.yml
since Ansible 2.5 instead of failing on a manually installed App you can specify accept_external_apps: true
> make homebrew_cask accept manual installed apps

- README.md
- tasks/main.yml
New Description
===============
This PR adds new variables `homebrew_user` and `homebrew_group` to enable users to specify an alternative user (and Unix group) when `ansible_user_id` is insufficient. See the conversation below for details.
Original Description
====================
If the default install path of `/usr/local` is used, then the user creating directories within that path must be root. 
My use case is that I create a `buildkite` user for use on our CI server as part of my role. The user does not exist at the start of my role, and I expect at the end of the process that the user will be unprivileged. 
I'd been doing the following to get this to work:
```yaml
roles:
- role: geerlingguy.homebrew
ansible_user_id: buildkite
become: yes
become_user: buildkite
```
Maybe I'm doing …
> Add homebrew_user and homebrew_group variables

- handlers/main.yml
- tasks/main.yml
This is a follow up for PR #111.
To avoid repetitious settings, this change moves several tasks
with identical privilege escalation settings (i.e. `become*`) into
a `block` structure.
Furthermore, privilege escalation need only be invoked if the
`homebrew_user` and `ansible_user_id` are mismatched, so this change
avoids unnecessary requests for privilege (e.g. `sudo -u`). In fact,
this helps preserve the original behavior prior to #111.
Finally, this change updates the handlers to run as the intended user.
> DRY up privilege escalation settings

- tasks/main.yml
Looping syntax is changing and so this change updates how looping
is peformed for future compatibility.
Since the `squash_actions` behavior in `with_X` loops has been
deprecated and will be removed in Ansible 2.11, there continues to
be noisy deprecation warnings. This persists even when attempting to
override the `squash_actions` setting to remove the `homebrew` module
from the [default list][default-squash-actions].
Fixes #110
[default-squash-actions]: https://docs.ansible.com/ansible/2.7/reference_appendices/config.html?highlight=squash_actions#default-squash-actions
> Use loop instead of with_items

- README.md
- tasks/main.yml
- tests/test.yml
The `homebrew_tap` module already supports pointing to a
non-github tap repository (by URL). This change adds support at
the role-level.
Fixes #90
> Support for Custom Taps

- README.md
- defaults/main.yml
Fixes #156.
When we run ansible-playbook on the M1 Mac, change the `homebrew_prefix` value to `/opt/homebrew`.
- [Installation — Homebrew Documentation](https://docs.brew.sh/Installation)
- [apple m1 - What is the difference between `ansible_architecture` and `ansible_machine` on Ansible? - Stack Overflow](https://stackoverflow.com/questions/66828315/what-is-the-difference-between-ansible-architecture-and-ansible-machine-on-a)
> Adjust the homebrew_prefix for M1 Mac
